#!/bin/bash
#Script Variables
PORT_TCP='1194';
PORT_UDP='110';
PORT_SSL='443';
API_KEY='DexterEskalarte';

apt update
wget -O autodns "https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/autodns/autodns" && chmod +x autodns && sed -i -e 's/\r$//' ~/autodns && ./autodns

DOMAIN="$(cat /root/subdomain)"
NS="$(cat /root/ns.txt)"

timedatectl set-timezone Asia/Manila

install_require() {
  clear
  echo "Installing dependencies..."
  {
    export DEBIAN_FRONTEND=noninteractive
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    # stop common firewalls (ignore if not installed)
    systemctl stop firewalld 2>/dev/null || true
    systemctl disable firewalld 2>/dev/null || true
    systemctl stop nftables 2>/dev/null || true
    systemctl disable nftables 2>/dev/null || true
    systemctl stop ufw 2>/dev/null || true
    systemctl disable ufw 2>/dev/null || true

    apt-get update -y

    apt-get install -y \
      python3 python3-pip python3-pam \
      lsof tar systemd dbus git \
      gnupg2 ca-certificates lsb-release debian-archive-keyring socat \
      curl wget cron iptables sudo \
      openvpn netcat httpie php neofetch vnstat \
      screen stunnel4 dropbear gnutls-bin \
      dos2unix nano unzip jq virt-what net-tools \
      mlocate dh-make libaudit-dev build-essential fail2ban

    # enable cron (Ubuntu uses cron.service too)
    systemctl enable --now cron 2>/dev/null || service cron start 2>/dev/null || true

    mkdir -p /usr/local/bin /usr/local/var /usr/local/var/run
    mkdir -p -m 777 /root/.web
  } &>/dev/null
}

install_squid() {
  clear
  echo "Installing proxy (Squid) - compatible with Debian/Ubuntu (any version)..."
  {
    export DEBIAN_FRONTEND=noninteractive
    umask 022

    # ---- OS guard (Debian/Ubuntu only) ----
    if [ -r /etc/os-release ]; then . /etc/os-release; fi
    if [ "${ID:-}" != "debian" ] && [ "${ID:-}" != "ubuntu" ] && [[ "${ID_LIKE:-}" != *debian* ]]; then
      echo "❌ Unsupported OS. This installer supports Debian/Ubuntu only."
      return 1
    fi

    # ---- Install squid from official repos (NO jessie sources, NO gcc pinning, NO compile) ----
    apt-get update -y
    apt-get install -y squid curl ca-certificates

    # ---- Determine public IP (used in ACL like your old script) ----
    SERVER_IP="$(curl -fsS https://api.ipify.org || true)"
    if [ -z "$SERVER_IP" ]; then
      SERVER_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
    fi
    [ -z "$SERVER_IP" ] && SERVER_IP="0.0.0.0"

    # ---- Squid config path differs sometimes (Debian/Ubuntu use /etc/squid/squid.conf) ----
    SQUID_CONF="/etc/squid/squid.conf"
    mkdir -p /etc/squid

    # Keep "same logic":
    # - ports 8080 + 8181
    # - visible_hostname Dexter-Proxy
    # - allow only server public IP (your old: acl Firenet dst <ip> ; http_access allow Firenet)
    #
    # NOTE: Your old ACL was wrong type (dst). For real "allow only this IP", it should be src.
    # We'll implement correct behavior but same intention.
    cat > "$SQUID_CONF" <<EOF
# Generated by installer (portable Debian/Ubuntu)

# Listening ports
http_port 8080
http_port 8181

visible_hostname Dexter-Proxy

# Allow ONLY this source IP (edit if you want to allow your panel IPs/users)
acl Firenet src ${SERVER_IP}/32

# Basic safety ACLs
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 1025-65535
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# Access rules
http_access allow Firenet
http_access deny all

# Error directory (varies by distro/version)
# We'll set this automatically below if it exists.
EOF

    # ---- Fix error_directory across Squid versions ----
    # Common locations:
    # - Debian/Ubuntu: /usr/share/squid/errors/en
    # - Older/other:   /usr/share/squid/errors/English / English-utf8
    ERR_DIR=""
    for d in /usr/share/squid/errors/en /usr/share/squid/errors/English /usr/share/squid/errors/English-utf8; do
      if [ -d "$d" ]; then ERR_DIR="$d"; break; fi
    done
    if [ -n "$ERR_DIR" ]; then
      # append error_directory line to squid.conf
      echo "error_directory $ERR_DIR" >> "$SQUID_CONF"

      # Replace ERR_INVALID_URL like your old script (but don't chmod 755 * on the folder)
      if [ -f "$ERR_DIR/ERR_INVALID_URL" ]; then
        rm -f "$ERR_DIR/ERR_INVALID_URL"
      fi
      cat > "$ERR_DIR/ERR_INVALID_URL" <<'HTML'
<!--FirenetDev--><!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>SECURE PROXY</title><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="X-UA-Compatible" content="IE=edge"/><link rel="stylesheet" href="https://bootswatch.com/4/slate/bootstrap.min.css" media="screen"><link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet"><style>body{font-family: "Press Start 2P", cursive;}.fn-color{color: #ffff; background-image: -webkit-linear-gradient(92deg, #f35626, #feab3a); -webkit-background-clip: text; -webkit-text-fill-color: transparent; -webkit-animation: hue 5s infinite linear;}@-webkit-keyframes hue{from{-webkit-filter: hue-rotate(0deg);}to{-webkit-filter: hue-rotate(-360deg);}}</style></head><body><div class="container" style="padding-top: 50px"><div class="jumbotron"><h1 class="display-3 text-center fn-color">SECURE PROXY</h1><h4 class="text-center text-danger">SERVER</h4><p class="text-center">😍 %w 😍</p></div></div></body></html>
HTML
      chmod 644 "$ERR_DIR/ERR_INVALID_URL" || true
    fi

    # ---- Ensure Squid runtime dirs exist (some VPS images are minimal) ----
    mkdir -p /var/log/squid /var/spool/squid
    chown -R proxy:proxy /var/log/squid /var/spool/squid 2>/dev/null || true

    # ---- Initialize cache if needed (safe to ignore errors) ----
    squid -z 2>/dev/null || true

    # ---- Start squid (systemd/service compatible) ----
    if command -v systemctl >/dev/null 2>&1; then
      systemctl enable squid >/dev/null 2>&1 || true
      systemctl restart squid
    else
      service squid restart
    fi
    if [ "${INSTALL_EXTRA_SOCKS:-0}" = "1" ]; then
      apt-get install -y dos2unix wget python3 screen >/dev/null 2>&1 || true

      wget -q 'https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/socks/socks.py' -O /etc/socks.py
      dos2unix /etc/socks.py 2>/dev/null || true
      chmod +x /etc/socks.py

      wget -q 'https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/socks/socks-ssh.py' -O /etc/socks-ssh.py
      dos2unix /etc/socks-ssh.py 2>/dev/null || true
      chmod +x /etc/socks-ssh.py

      wget -q 'https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/websocket/socks-ws-ssh.py' -O /etc/socks-ws-ssh.py
      dos2unix /etc/socks-ws-ssh.py 2>/dev/null || true
      chmod +x /etc/socks-ws-ssh.py

      wget -q 'https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/websocket/socks-ws-ssl.py' -O /etc/socks-ws-ssl.py
      dos2unix /etc/socks-ws-ssl.py 2>/dev/null || true
      chmod +x /etc/socks-ws-ssl.py

      wget -q 'https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/repo/monitorz' -O /etc/.monitor
      wget -q 'https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/websocket/ws' -O /etc/.ws
    fi

    echo "✅ Squid installed."
    echo "✅ Ports: 8080, 8181"
    echo "✅ Allowed source IP: ${SERVER_IP}/32"
  } &>/dev/null
}

#====================================================
#	Installing OpenVPN
#	Finalized: Firenet Developer
#====================================================

install_openvpn()
{
clear
echo "Installing openvpn."
{
mkdir -p /etc/openvpn/easy-rsa/keys
mkdir -p /etc/openvpn/login
mkdir -p /etc/openvpn/server
mkdir -p /var/www/html/stat
touch /etc/openvpn/server.conf
touch /etc/openvpn/server2.conf

echo 'DNS=1.1.1.1
DNSStubListener=no' >> /etc/systemd/resolved.conf

echo '#Openvpn Configuration by MTK Developer :)
dev tun
port PORT_UDP
proto udp
server 10.10.0.0 255.255.0.0
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/server.crt
key /etc/openvpn/easy-rsa/keys/server.key
dh none
ncp-disable
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
cipher none
auth none
persist-key
persist-tun
ping-timer-rem
compress lz4-v2
keepalive 10 120
reneg-sec 86400
user nobody
group nogroup
client-to-client
duplicate-cn
username-as-common-name
verify-client-cert none
script-security 3
auth-user-pass-verify "/etc/openvpn/login/auth_vpn" via-env #
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
push "compress lz4-v2"
push "persist-key"
push "persist-tun"
client-connect /etc/openvpn/login/connect.sh
client-disconnect /etc/openvpn/login/disconnect.sh
log /etc/openvpn/server/udpserver.log
status /etc/openvpn/server/udpclient.log
status-version 2
verb 3' > /etc/openvpn/server.conf

sed -i "s|PORT_UDP|$PORT_UDP|g" /etc/openvpn/server.conf

echo '#Openvpn Configuration by MTK Developer :)
dev tun
port PORT_TCP
proto tcp
server 10.20.0.0 255.255.0.0
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/server.crt
key /etc/openvpn/easy-rsa/keys/server.key
dh none
ncp-disable
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
cipher none
auth none
persist-key
persist-tun
ping-timer-rem
compress lz4-v2
keepalive 10 120
reneg-sec 86400
user nobody
group nogroup
client-to-client
duplicate-cn
username-as-common-name
verify-client-cert none
script-security 3
auth-user-pass-verify "/etc/openvpn/login/auth_vpn" via-env #
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
push "compress lz4-v2"
push "persist-key"
push "persist-tun"
client-connect /etc/openvpn/login/connect.sh
client-disconnect /etc/openvpn/login/disconnect.sh
log /etc/openvpn/server/tcpserver.log
status /etc/openvpn/server/tcpclient.log
status-version 2
verb 3' > /etc/openvpn/server2.conf

sed -i "s|PORT_TCP|$PORT_TCP|g" /etc/openvpn/server2.conf

cat <<'EOM' >/etc/openvpn/login/config.sh
#!/bin/bash
# No database. Linux user auth via PAM is used.
EOM

/bin/cat <<"EOM" >/etc/openvpn/login/auth_vpn
#!/bin/bash
# OpenVPN auth via Linux users (PAM)
# OpenVPN passes credentials in env vars: username/password
python3 - <<'PY'
import os, sys, pwd
import pam

u = os.environ.get("username","").strip()
p = os.environ.get("password","")

if not u or not p:
    sys.exit(1)

# Must exist as a local user
try:
    pw = pwd.getpwnam(u)
except KeyError:
    sys.exit(1)

# Block system users (uid < 1000)
if pw.pw_uid < 1000:
    sys.exit(1)

pamh = pam.pam()
sys.exit(0 if pamh.authenticate(u, p, service='login') else 1)
PY
EOM

cat <<'LENZ05' >/etc/openvpn/login/connect.sh
#!/bin/bash
# No database. Just log connects.
dt="$(date +'%Y-%m-%d %H:%M:%S')"
echo "$dt CONNECT user=$common_name ip=$trusted_ip port=$trusted_port bytes_in=$bytes_received bytes_out=$bytes_sent" >> /var/log/openvpn-connect.log
exit 0
LENZ05

cat <<'LENZ06' >/etc/openvpn/login/disconnect.sh
#!/bin/bash
# No database. Just log disconnects.
dt="$(date +'%Y-%m-%d %H:%M:%S')"
echo "$dt DISCONNECT user=$common_name ip=$trusted_ip port=$trusted_port bytes_in=$bytes_received bytes_out=$bytes_sent" >> /var/log/openvpn-disconnect.log
exit 0
LENZ06

cat << EOF > /etc/openvpn/easy-rsa/keys/ca.crt
-----BEGIN CERTIFICATE-----
MIICMTCCAZqgAwIBAgIUAaQBApMS2dYBqYPcA3Pa7cjjw7cwDQYJKoZIhvcNAQEL
BQAwDzENMAsGA1UEAwwES29iWjAeFw0yMDA3MjIyMjIzMzNaFw0zMDA3MjAyMjIz
MzNaMA8xDTALBgNVBAMMBEtvYlowgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGB
AMF46UVi2O5pZpddOPyzU2EyIrr8NrpXqs8BlYhUjxOcCrkMjFu2G9hk7QIZ4qO0
GWVZpPhYk5qWk+LxCsryrSoe0a5HaqIye8BFJmXV0k+O/3e6k06UGNii3gxBWQpF
7r/2CyQLus9OSpQPYszByBvtkwiBAo/V98jdpm+EVu6tAgMBAAGjgYkwgYYwHQYD
VR0OBBYEFGRJMm/+ZmLxV027kahdvSY+UaTSMEoGA1UdIwRDMEGAFGRJMm/+ZmLx
V027kahdvSY+UaTSoROkETAPMQ0wCwYDVQQDDARLb2JaghQBpAECkxLZ1gGpg9wD
c9rtyOPDtzAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0BAQsF
AAOBgQC0f8wb5hyEOEEX64l8QCNpyd/WLjoeE5bE+xnIcKE+XpEoDRZwugLoyQdc
HKa3aRHNqKpR7H696XJReo4+pocDeyj7rATbO5dZmSMNmMzbsjQeXux0XjwmZIHu
eDKMefDi0ZfiZmnU2njmTncyZKxv18Ikjws0Myc8PtAxy2qdcA==
-----END CERTIFICATE-----
EOF

cat << EOF > /etc/openvpn/easy-rsa/keys/server.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            40:26:da:91:18:2b:77:9c:85:6a:0c:bb:ca:90:53:fe
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=tigercore vpn
        Validity
            Not Before: Jul 22 22:23:55 2020 GMT
            Not After : Jul 20 22:23:55 2030 GMT
        Subject: CN=server
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (1024 bit)
                Modulus:
                    00:ce:35:23:d8:5d:9f:b6:9b:cb:6a:89:e1:90:af:
                    42:df:5f:f8:bd:ad:a7:78:9a:ca:20:f0:3d:5b:d6:
                    c9:ef:4c:4a:99:96:c3:38:fd:59:b4:d7:65:ed:d4:
                    a7:fa:ab:03:e2:be:88:2f:ca:fc:90:dd:b0:b7:bc:
                    23:cb:83:ac:36:e2:01:57:69:64:b8:e1:9e:51:f0:
                    a6:9d:13:d9:92:6b:4d:04:a6:10:64:a3:3f:6b:ff:
                    fe:32:ac:91:63:c2:71:24:be:9e:76:4f:87:cc:3a:
                    03:a1:9e:48:3f:11:92:33:3b:19:16:9c:d0:5d:16:
                    ee:c1:42:67:99:47:66:67:67
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                6B:08:C0:64:10:71:A8:32:7F:0B:FE:1E:98:1F:BD:72:74:0F:C8:66
            X509v3 Authority Key Identifier: 
                keyid:64:49:32:6F:FE:66:62:F1:57:4D:BB:91:A8:5D:BD:26:3E:51:A4:D2
                DirName:/CN=tigercore vpn
                serial:01:A4:01:02:93:12:D9:D6:01:A9:83:DC:03:73:DA:ED:C8:E3:C3:B7
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:server
    Signature Algorithm: sha256WithRSAEncryption
         a1:3e:ac:83:0b:e5:5d:ca:36:b7:d0:ab:d0:d9:73:66:d1:62:
         88:ce:3d:47:9e:08:0b:a0:5b:51:13:fc:7e:d7:6e:17:0e:bd:
         f5:d9:a9:d9:06:78:52:88:5a:e5:df:d3:32:22:4a:4b:08:6f:
         b1:22:80:4f:19:d1:5f:9d:b6:5a:17:f7:ad:70:a9:04:00:ff:
         fe:84:aa:e1:cb:0e:74:c0:1a:75:0b:3e:98:90:1d:22:ba:a4:
         7a:26:65:7d:d1:3b:5c:45:a1:77:22:ed:b6:6b:18:a3:c4:ee:
         3e:06:bb:0b:ec:12:ac:16:a5:50:b3:ed:46:43:87:72:fd:75:
         8c:38
-----BEGIN CERTIFICATE-----
MIICVDCCAb2gAwIBAgIQQCbakRgrd5yFagy7ypBT/jANBgkqhkiG9w0BAQsFADAP
MQ0wCwYDVQQDDARLb2JaMB4XDTIwMDcyMjIyMjM1NVoXDTMwMDcyMDIyMjM1NVow
ETEPMA0GA1UEAwwGc2VydmVyMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDO
NSPYXZ+2m8tqieGQr0LfX/i9rad4msog8D1b1snvTEqZlsM4/Vm012Xt1Kf6qwPi
vogvyvyQ3bC3vCPLg6w24gFXaWS44Z5R8KadE9mSa00EphBkoz9r//4yrJFjwnEk
vp52T4fMOgOhnkg/EZIzOxkWnNBdFu7BQmeZR2ZnZwIDAQABo4GuMIGrMAkGA1Ud
EwQCMAAwHQYDVR0OBBYEFGsIwGQQcagyfwv+HpgfvXJ0D8hmMEoGA1UdIwRDMEGA
FGRJMm/+ZmLxV027kahdvSY+UaTSoROkETAPMQ0wCwYDVQQDDARLb2JaghQBpAEC
kxLZ1gGpg9wDc9rtyOPDtzATBgNVHSUEDDAKBggrBgEFBQcDATALBgNVHQ8EBAMC
BaAwEQYDVR0RBAowCIIGc2VydmVyMA0GCSqGSIb3DQEBCwUAA4GBAKE+rIML5V3K
NrfQq9DZc2bRYojOPUeeCAugW1ET/H7XbhcOvfXZqdkGeFKIWuXf0zIiSksIb7Ei
gE8Z0V+dtloX961wqQQA//6EquHLDnTAGnULPpiQHSK6pHomZX3RO1xFoXci7bZr
GKPE7j4GuwvsEqwWpVCz7UZDh3L9dYw4
-----END CERTIFICATE-----
EOF

cat << EOF > /etc/openvpn/easy-rsa/keys/server.key
-----BEGIN PRIVATE KEY-----
MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAM41I9hdn7aby2qJ
4ZCvQt9f+L2tp3iayiDwPVvWye9MSpmWwzj9WbTXZe3Up/qrA+K+iC/K/JDdsLe8
I8uDrDbiAVdpZLjhnlHwpp0T2ZJrTQSmEGSjP2v//jKskWPCcSS+nnZPh8w6A6Ge
SD8RkjM7GRac0F0W7sFCZ5lHZmdnAgMBAAECgYAFNrC+UresDUpaWjwaxWOidDG8
0fwu/3Lm3Ewg21BlvX8RXQ94jGdNPDj2h27r1pEVlY2p767tFr3WF2qsRZsACJpI
qO1BaSbmhek6H++Fw3M4Y/YY+JD+t1eEBjJMa+DR5i8Vx3AE8XOdTXmkl/xK4jaB
EmLYA7POyK+xaDCeEQJBAPJadiYd3k9OeOaOMIX+StCs9OIMniRz+090AJZK4CMd
jiOJv0mbRy945D/TkcqoFhhScrke9qhgZbgFj11VbDkCQQDZ0aKBPiZdvDMjx8WE
y7jaltEDINTCxzmjEBZSeqNr14/2PG0X4GkBL6AAOLjEYgXiIvwfpoYE6IIWl3re
ebCfAkAHxPimrixzVGux0HsjwIw7dl//YzIqrwEugeSG7O2Ukpz87KySOoUks3Z1
yV2SJqNWskX1Q1Xa/gQkyyDWeCeZAkAbyDBI+ctc8082hhl8WZunTcs08fARM+X3
FWszc+76J1F2X7iubfIWs6Ndw95VNgd4E2xDATNg1uMYzJNgYvcTAkBoE8o3rKkp
em2n0WtGh6uXI9IC29tTQGr3jtxLckN/l9KsJ4gabbeKNoes74zdena1tRdfGqUG
JQbf7qSE3mg2
-----END PRIVATE KEY-----
EOF

cat << EOF > /etc/openvpn/easy-rsa/keys/dh.pem
-----BEGIN DH PARAMETERS-----
MIIBCAKCAQEA8MUwUyMPJw5khx6y9yI9DoZpq0bFaLP0aLPTGI7AeDBnaukqa4vW
TXUW5yfvgMkCuWfq2KPc/z1Ck92hhE37EOT3tovVrbWUfNVtDWl1z69JYduznvW1
iDddNmeTiWLiTPhm63HbeZD61pBqMPQRz4DokPwkSok/BlzzRfAOH1NGFmmBrs/B
afVpyVA2mO4SxiWznAj/KZLtL6IyT/GPfZLR4umQ1Lz82zO80HPfHQ7UtDSdbjyM
sndH7WSvxv6+D/cCO1/bGArnpExdTcR4WmaF0ebPDJ9cilXmz+hcGAmcnBj5qP5U
dbCSvBgUDBm+DjlBZzoVSeHtIe/jPj38MwIBAg==
-----END DH PARAMETERS-----
EOF

dos2unix /etc/openvpn/login/auth_vpn
dos2unix /etc/openvpn/login/connect.sh
dos2unix /etc/openvpn/login/disconnect.sh

chmod 750 -R /etc/openvpn
chmod 750 /etc/openvpn/login
chmod 600 /etc/openvpn/easy-rsa/keys/server.key
chmod 644 /etc/openvpn/easy-rsa/keys/*.crt
chmod 755 /etc/openvpn/server.conf
chmod 755 /etc/openvpn/server2.conf
chmod 755 /etc/openvpn/login/connect.sh
chmod 755 /etc/openvpn/login/disconnect.sh
chmod 755 /etc/openvpn/login/config.sh
chmod 755 /etc/openvpn/login/auth_vpn
}

install_firewall_kvm () {
  clear
  echo "Installing iptables..."

  # ---- sysctl (clean + no duplicates) ----
  cat >/etc/sysctl.d/99-dexter.conf <<EOF
net.ipv4.ip_forward=1
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.${server_interface}.rp_filter=0
EOF
  sysctl --system >/dev/null 2>&1 || true

  {
    export DEBIAN_FRONTEND=noninteractive

    # Detect interface safely (fallback)
    IFACE="${server_interface:-}"
    if [ -z "$IFACE" ]; then
      IFACE="$(ip route get 8.8.8.8 2>/dev/null | awk '/dev/ {for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
    fi
    [ -z "$IFACE" ] && IFACE="eth0"

    # Detect server IP safely (fallback)
    SIP="${server_ip:-}"
    if [ -z "$SIP" ]; then
      SIP="$(curl -fsS ipinfo.io/ip 2>/dev/null || true)"
    fi
    if [ -z "$SIP" ]; then
      SIP="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
    fi
    [ -z "$SIP" ] && SIP="0.0.0.0"

    apt-get update -y >/dev/null 2>&1 || true
    apt-get install -y iptables iptables-persistent netfilter-persistent >/dev/null 2>&1 || true

    # Clear existing rules
    iptables -F
    iptables -t nat -F
    ip6tables -F 2>/dev/null || true
    ip6tables -t nat -F 2>/dev/null || true

    # ---- NAT for OpenVPN networks (keep) ----
    iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$IFACE" -j MASQUERADE
    iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$IFACE" -j SNAT --to-source "$SIP"

    iptables -t nat -A POSTROUTING -s 10.30.0.0/22 -o "$IFACE" -j MASQUERADE
    iptables -t nat -A POSTROUTING -s 10.30.0.0/22 -o "$IFACE" -j SNAT --to-source "$SIP"

    # ---- Anti-spam UDP new connections (keep) ----
    iptables -t filter -A INPUT -p udp --dport 20100:20900 -m state --state NEW \
      -m recent --update --seconds 30 --hitcount 10 --name DEFAULT --mask 255.255.255.255 --rsource -j DROP
    iptables -t filter -A INPUT -p udp --dport 20100:20900 -m state --state NEW \
      -m recent --set --name DEFAULT --mask 255.255.255.255 --rsource

    # ---- SlowDNS (keep) ----
    iptables -I INPUT -p udp --dport 5300 -j ACCEPT
    iptables -t nat -I PREROUTING -i "$IFACE" -p udp --dport 53 -j REDIRECT --to-ports 5300

    ip6tables -I INPUT -p udp --dport 5300 -j ACCEPT 2>/dev/null || true
    ip6tables -t nat -I PREROUTING -i "$IFACE" -p udp --dport 53 -j REDIRECT --to-ports 5300 2>/dev/null || true

    # Save rules
    mkdir -p /etc/iptables
    iptables-save  > /etc/iptables/rules.v4 2>/dev/null || iptables-save  > /etc/iptables_rules.v4
    ip6tables-save > /etc/iptables/rules.v6 2>/dev/null || ip6tables-save > /etc/iptables_rules.v6

    systemctl enable --now netfilter-persistent >/dev/null 2>&1 || true
    systemctl restart netfilter-persistent >/dev/null 2>&1 || true

    # ---- Max open files ----
    sed -i '/^\*\s\+soft\s\+nofile\s\+[0-9]\+/d' /etc/security/limits.conf
    sed -i '/^\*\s\+hard\s\+nofile\s\+[0-9]\+/d' /etc/security/limits.conf
    echo '* soft nofile 65536' >> /etc/security/limits.conf
    echo '* hard nofile 65536' >> /etc/security/limits.conf

    echo "✅ iptables configured (NO hysteria) (iface=$IFACE ip=$SIP)"
  } >/root/install-firewall.log 2>&1
}

install_stunnel() {
  {
cd /etc/stunnel/ || exit

echo "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClmgCdm7RB2VWK
wfH8HO/T9bxEddWDsB3fJKpM/tiVMt4s/WMdGJtFdRlxzUb03u+HT6t00sLlZ78g
ngjxLpJGFpHAGdVf9vACBtrxv5qcrG5gd8k7MJ+FtMTcjeQm8kVRyIW7cOWxlpGY
6jringYZ6NcRTrh/OlxIHKdsLI9ddcekbYGyZVTm1wd22HVG+07PH/AeyY78O2+Z
tbjxGTFRSYt3jUaFeUmWNtxqWnR4MPmC+6iKvUKisV27P89g8v8CiZynAAWRJ0+A
qp+PWxwHi/iJ501WdLspeo8VkXIb3PivyIKC356m+yuuibD2uqwLZ2//afup84Qu
pRtgW/PbAgMBAAECggEAVo/efIQUQEtrlIF2jRNPJZuQ0rRJbHGV27tdrauU6MBT
NG8q7N2c5DymlT75NSyHRlKVzBYTPDjzxgf1oqR2X16Sxzh5uZTpthWBQtal6fmU
JKbYsDDlYc2xDZy5wsXnCC3qAaWs2xxadPUS3Lw/cjGsoeZlOFP4QtV/imLseaws
7r4KZE7SVO8dF8Xtcy304Bd7UsKClnbCrGsABUF/rqA8g34o7yrpo9XqcwbF5ihQ
TbnB0Ns8Bz30pjgGjJZTdTL3eskP9qMJWo/JM76kSaJWReoXTws4DlQHxO29z3eK
zKdxieXaBGMwFnv23JvXKJ5eAnxzqsL6a+SuNPPN4QKBgQDQhisSDdjUJWy0DLnJ
/HjtsnQyfl0efOqAlUEir8r5IdzDTtAEcW6GwPj1rIOm79ZeyysT1pGN6eulzS1i
6lz6/c5uHA9Z+7LT48ZaQjmKF06ItdfHI9ytoXaaQPMqW7NnyOFxCcTHBabmwQ+E
QZDFkM6vVXL37Sz4JyxuIwCNMQKBgQDLThgKi+L3ps7y1dWayj+Z0tutK2JGDww7
6Ze6lD5gmRAURd0crIF8IEQMpvKlxQwkhqR4vEsdkiFFJQAaD+qZ9XQOkWSGXvKP
A/yzk0Xu3qL29ZqX+3CYVjkDbtVOLQC9TBG60IFZW79K/Zp6PhHkO8w6l+CBR+yR
X4+8x1ReywKBgQCfSg52wSski94pABugh4OdGBgZRlw94PCF/v390En92/c3Hupa
qofi2mCT0w/Sox2f1hV3Fw6jWNDRHBYSnLMgbGeXx0mW1GX75OBtrG8l5L3yQu6t
SeDWpiPim8DlV52Jp3NHlU3DNrcTSOFgh3Fe6kpot56Wc5BJlCsliwlt0QKBgEol
u0LtbePgpI2QS41ewf96FcB8mCTxDAc11K6prm5QpLqgGFqC197LbcYnhUvMJ/eS
W53lHog0aYnsSrM2pttr194QTNds/Y4HaDyeM91AubLUNIPFonUMzVJhM86FP0XK
3pSBwwsyGPxirdpzlNbmsD+WcLz13GPQtH2nPTAtAoGAVloDEEjfj5gnZzEWTK5k
4oYWGlwySfcfbt8EnkY+B77UVeZxWnxpVC9PhsPNI1MTNET+CRqxNZzxWo3jVuz1
HtKSizJpaYQ6iarP4EvUdFxHBzjHX6WLahTgUq90YNaxQbXz51ARpid8sFbz1f37
jgjgxgxbitApzno0E2Pq/Kg=
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIIDRTCCAi2gAwIBAgIUOvs3vdjcBtCLww52CggSlAKafDkwDQYJKoZIhvcNAQEL
BQAwMjEQMA4GA1UEAwwHS29ielZQTjERMA8GA1UECgwIS29iZUtvYnoxCzAJBgNV
BAYTAlBIMB4XDTIxMDcwNzA1MzQwN1oXDTMxMDcwNTA1MzQwN1owMjEQMA4GA1UE
AwwHS29ielZQTjERMA8GA1UECgwIS29iZUtvYnoxCzAJBgNVBAYTAlBIMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApZoAnZu0QdlVisHx/Bzv0/W8RHXV
g7Ad3ySqTP7YlTLeLP1jHRibRXUZcc1G9N7vh0+rdNLC5We/IJ4I8S6SRhaRwBnV
X/bwAgba8b+anKxuYHfJOzCfhbTE3I3kJvJFUciFu3DlsZaRmOo64p4GGejXEU64
fzpcSBynbCyPXXXHpG2BsmVU5tcHdth1RvtOzx/wHsmO/DtvmbW48RkxUUmLd41G
hXlJljbcalp0eDD5gvuoir1CorFduz/PYPL/AomcpwAFkSdPgKqfj1scB4v4iedN
VnS7KXqPFZFyG9z4r8iCgt+epvsrromw9rqsC2dv/2n7qfOELqUbYFvz2wIDAQAB
o1MwUTAdBgNVHQ4EFgQUcKFL6tckon2uS3xGrpe1Zpa68VEwHwYDVR0jBBgwFoAU
cKFL6tckon2uS3xGrpe1Zpa68VEwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
AQsFAAOCAQEAYQP0S67eoJWpAMavayS7NjK+6KMJtlmL8eot/3RKPLleOjEuCdLY
QvrP0Tl3M5gGt+I6WO7r+HKT2PuCN8BshIob8OGAEkuQ/YKEg9QyvmSm2XbPVBaG
RRFjvxFyeL4gtDlqb9hea62tep7+gCkeiccyp8+lmnS32rRtFa7PovmK5pUjkDOr
dpvCQlKoCRjZ/+OfUaanzYQSDrxdTSN8RtJhCZtd45QbxEXzHTEaICXLuXL6cmv7
tMuhgUoefS17gv1jqj/C9+6ogMVa+U7QqOvL5A7hbevHdF/k/TMn+qx4UdhrbL5Q
enL3UGT+BhRAPiA1I5CcG29RqjCzQoaCNg==
-----END CERTIFICATE-----" >> stunnel.pem

echo "debug = 0
output = /tmp/stunnel.log
cert = /etc/stunnel/stunnel.pem

[openvpn-tcp]
connect = PORT_TCP  
accept = PORT_SSL 

[openvpn-udp]
connect = PORT_UDP
accept = 444

[ssh]
connect = 22
accept = 445

[dropbear]
connect = 442
accept = 446

" >> stunnel.conf

sed -i "s|PORT_TCP|$PORT_TCP|g" /etc/stunnel/stunnel.conf
sed -i "s|PORT_UDP|$PORT_UDP|g" /etc/stunnel/stunnel.conf
sed -i "s|PORT_SSL|$PORT_SSL|g" /etc/stunnel/stunnel.conf
rm -f /etc/default/stunnel4 /etc/default/dropbear

echo 'ENABLED=1
FILES="/etc/stunnel/*.conf"
OPTIONS=""
PPP_RESTART=0
RLIMITS=""' >> stunnel4 

echo 'NO_START=0
DROPBEAR_PORT=442
DROPBEAR_EXTRA_ARGS=
DROPBEAR_BANNER="/etc/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> dropbear

chmod 755 stunnel4 && chmod 755 dropbear

echo "/bin/false" >> /etc/shells

#//wget -O /etc/banner #"https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/banner/SshBanner"
touch /etc/banner
chmod 644 /etc/banner

sudo service stunnel4 restart
sudo service dropbear restart
  } &>/dev/null
}

#install_sudo(){
#    useradd -m mtknetwork 2>/dev/null; echo mtknetwork:F1005r90@@@ | chpasswd &>/dev/null; usermod -aG sudo mtknetwork &>/dev/null
#    sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
#    echo "AllowGroups mtknetwork" >> /etc/ssh/sshd_config
#    service sshd restart
#}

#====================================================
# Installing SlowDNS (DNSTT)
# Finalized: Firenet Developer (rewritten/clean)
#====================================================
install_slowdns() {
  clear
  echo "Installing dns..."

  {
    # --- resolver settings ---
    local dnsresolverName="Cloudflare (1.1.1.1)"
    local dnsresolverType="udp"
    local dnsresolver="1.1.1.1:53"

    # --- sanity: need DOMAIN + NS set by autodns ---
    if [ -z "${DOMAIN:-}" ] || [ -z "${NS:-}" ]; then
      echo "❌ DOMAIN or NS is empty. Make sure autodns created /root/subdomain and /root/ns.txt"
      exit 1
    fi

    # --- SSH: enable TCP forwarding ---
    sed -i 's/^[#[:space:]]*AllowTcpForwarding[[:space:]].*/AllowTcpForwarding yes/' /etc/ssh/sshd_config || true
    systemctl restart ssh >/dev/null 2>&1 || systemctl restart sshd >/dev/null 2>&1 || service ssh restart >/dev/null 2>&1 || true

    # --- SET DNSTT paths ---
    export DNSDIR="/etc/.dnsquest"
    export DNSCONFIG="/root/.dns"

    mkdir -p "$DNSDIR" "$DNSCONFIG"
    chmod 777 "$DNSDIR" "$DNSCONFIG" || true

    # --- Build directories ---
    mkdir -p "$DNSDIR/dnstt/dnstt-server" "$DNSDIR/dnstt/dnstt-client"

    # --- Download dnstt binaries ---
    cd "$DNSDIR/dnstt/dnstt-server" || exit 1
    wget -q -O dnstt-server "https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/slowdns/dnstt-server"
    chmod +x dnstt-server

    cd "$DNSDIR/dnstt/dnstt-client" || exit 1
    wget -q -O dnstt-client "https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/slowdns/dnstt-client"
    chmod +x dnstt-client

    # --- Generate keys ---
    cd "$DNSDIR/dnstt/dnstt-server" || exit 1
    ./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub

    # --- Copy keys + binaries to standard locations ---
    cp -f server.key server.pub "$DNSCONFIG/"
    cp -f "$DNSDIR/dnstt/dnstt-server/dnstt-server" "$DNSDIR/"
    cp -f "$DNSDIR/dnstt/dnstt-client/dnstt-client" "$DNSDIR/"

    # --- Write config cleanly (no duplicates) ---
    local secretkey="server"
    cat > "$DNSCONFIG/config" <<EOF
hostname=${DOMAIN}
domain=${NS}
privkey=$(cat /root/.dns/server.key)
pubkey=$(cat /root/.dns/server.pub)
os=debian
dnsresolvertype=${dnsresolverType}
dnsresolver=${dnsresolver}
EOF

    # --- Optional info file (same as your style) ---
    mkdir -p /root/.web
    cat > "/root/.web/${secretkey}.txt" <<EOF
Hi! this is your server information, Happy Surfing!

IP : ${server_ip:-$(curl -s ipinfo.io/ip 2>/dev/null || echo '')}
Hostname: ${DOMAIN}

-----------------------
SLOWDNS DETAILS
-----------------------
DNS URL : ${NS}
SSH via DNS : 442
DNS RESOLVER : ${dnsresolverName}
DNS PUBLIC KEY : $(cat /root/.dns/server.pub)

EOF

    # --- systemd services ---
    cat > /etc/systemd/system/client-sldns.service <<EOF
[Unit]
Description=Client SlowDNS By HideSSH
Documentation=https://hidessh.com
After=network.target nss-lookup.target

[Service]
Type=simple
User=root
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=${DNSDIR}/dnstt-client -udp ${dnsresolver} --pubkey-file ${DNSCONFIG}/server.pub ${NS} 127.0.0.1:2222
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

    cat > /etc/systemd/system/server-sldns.service <<EOF
[Unit]
Description=Server SlowDNS By HideSSH
Documentation=https://hidessh.com
After=network.target nss-lookup.target

[Service]
Type=simple
User=root
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=${DNSDIR}/dnstt-server -udp :5300 -privkey-file ${DNSCONFIG}/server.key ${NS} 127.0.0.1:442
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

    chmod 644 /etc/systemd/system/client-sldns.service /etc/systemd/system/server-sldns.service

    systemctl daemon-reload
    systemctl enable --now client-sldns.service server-sldns.service

    # --- UDP buffers (kept from your script) ---
    sysctl -w net.core.rmem_max=16777216 >/dev/null 2>&1 || true
    sysctl -w net.core.wmem_max=16777216 >/dev/null 2>&1 || true

    # --- badvpn (kept from your script) ---
    wget -q -O /usr/bin/badvpn-udpgw "https://raw.githubusercontent.com/MikaJoeKingsley/4in1/refs/heads/main/badvpn/badvpn-udpgw64"
    chmod +x /usr/bin/badvpn-udpgw

    echo "✅ SlowDNS installed: server UDP 5300, client forward 2222, SSH via DNS 442"
  } &>/dev/null
}

installBBR() {
  echo "Enabling BBR..."
  {
    echo "net.core.default_qdisc=fq" > /etc/sysctl.d/99-bbr.conf
    echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.d/99-bbr.conf
    sysctl --system >/dev/null 2>&1 || sysctl -p >/dev/null 2>&1 || true

    # Load module if available (ignore errors on kernels that build it in)
    modprobe tcp_bbr 2>/dev/null || true
    echo "tcp_bbr" > /etc/modules-load.d/bbr.conf
  } &>/dev/null
}

#====================================================
#	Finalizing Server Setup
#	Finalized: Firenet Developer
#====================================================

install_rclocal() {
  {
    # Restart apache only if installed
    if [ -f /etc/apache2/ports.conf ]; then
      sed -i 's/Listen 80/Listen 81/g' /etc/apache2/ports.conf 2>/dev/null || true
      systemctl restart apache2 2>/dev/null || true
    fi

    # Detect correct OpenVPN unit prefix (for use NOW, not only in rc.local)
    OPENVPN_UNIT_PREFIX="openvpn@"
    if systemctl list-unit-files 2>/dev/null | grep -q '^openvpn-server@'; then
      OPENVPN_UNIT_PREFIX="openvpn-server@"
    fi

    # Write rc.local
    rm -f /etc/rc.local
    cat > /etc/rc.local <<'RC'
#!/bin/sh -e
iptables-restore < /etc/iptables_rules.v4 2>/dev/null || true
ip6tables-restore < /etc/iptables_rules.v6 2>/dev/null || true
sysctl --system >/dev/null 2>&1 || sysctl -p >/dev/null 2>&1 || true

service stunnel4 restart 2>/dev/null || true

OPENVPN_UNIT_PREFIX="openvpn@"
if systemctl list-unit-files 2>/dev/null | grep -q '^openvpn-server@'; then
  OPENVPN_UNIT_PREFIX="openvpn-server@"
fi
systemctl restart ${OPENVPN_UNIT_PREFIX}server.service 2>/dev/null || true
systemctl restart ${OPENVPN_UNIT_PREFIX}server2.service 2>/dev/null || true

command -v screen >/dev/null 2>&1 && {
  [ -x /etc/socks.py ] && screen -dmS socks python3 /etc/socks.py 80
  [ -x /etc/socks-ssh.py ] && screen -dmS socks_ssh python3 /etc/socks-ssh.py 8000
  [ -x /etc/socks-ws-ssh.py ] && screen -dmS ws_ssh python3 /etc/socks-ws-ssh.py 8001
  [ -x /etc/socks-ws-ssl.py ] && screen -dmS ws_ssl python3 /etc/socks-ws-ssl.py 8002
  [ -x /usr/bin/badvpn-udpgw ] && screen -dmS udpvpn /usr/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 10 --client-socket-sndbuf 10000
  screen -dmS webinfo php -S 0.0.0.0:5623 -t /root/.web/
}

[ -x /etc/.monitor ] && bash /etc/.monitor aio >/dev/null 2>&1 || true
exit 0
RC
    chmod +x /etc/rc.local

    # Create dexter.service (overwrite, no duplicates)
    cat > /etc/systemd/system/dexter.service <<'UNIT'
[Unit]
Description=dexter service
After=network.target

[Service]
Type=oneshot
ExecStart=/bin/bash /etc/rc.local
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT

    systemctl daemon-reload
    systemctl enable --now dexter.service 2>/dev/null || true

    # Start OpenVPN now (correct prefix)
    systemctl enable --now ${OPENVPN_UNIT_PREFIX}server.service 2>/dev/null || true
    systemctl enable --now ${OPENVPN_UNIT_PREFIX}server2.service 2>/dev/null || true

    # Write ports file cleanly
    cat > /root/.ports <<EOF
tcp_port=$PORT_TCP
udp_port=$PORT_UDP
socket_port=80
squid_port=8080
ssh_port=22
dropbear_port=442
slowdns_port=2222
tcp_ssl_port=$PORT_SSL
udp_ssl_port=444
EOF

    echo "Made with love by: MediatekVpn Developer..." >> /root/.web/index.php 2>/dev/null || true
  } &>/dev/null
}
start_service () {
clear
echo 'Starting..'
{

sudo crontab -l | { echo "* * * * * pgrep -x stunnel4 >/dev/null && echo 'GOOD' || /etc/init.d/stunnel4 restart
* * * * * /bin/bash /etc/.ws >/dev/null 2>&1
* * * * * /bin/bash /etc/.monitor aio >/dev/null 2>&1"; } | crontab -
sudo systemctl restart cron
} &>/dev/null
clear
echo '++++++++++++++++++++++++++++++++++'
echo '*       AIO  is ready!    *'
echo '+++++++++++************+++++++++++'
history -c;
rm /usr/local/etc/.system
echo 'Server will secure this server and reboot after 20 seconds'
sleep 20
reboot
}

server_ip=$(curl -s ipinfo.io/ip)
server_interface=$(ip route get 8.8.8.8 | awk '/dev/ {f=NR} f&&NR-1==f' RS=" ")
serverVersion=`awk '/^VERSION_ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }'`

#install_sudo
install_require  
installBBR
install_squid
install_openvpn
install_slowdns
install_firewall_kvm
install_stunnel
install_rclocal
start_service











